name: physicscode

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  physicscode:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /physicscode') ||
      startsWith(github.event.comment.body, '/physicscode')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run physicscode
        uses: anomalyco/physicscode/github@latest
        env:
          PHYSICSCODE_API_KEY: ${{ secrets.PHYSICSCODE_API_KEY }}
          PHYSICSCODE_PERMISSION: '{"bash": "deny"}'
        with:
          model: physicscode/claude-opus-4-5
