import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const PHYSICSCODE_EXPERIMENTAL = truthy("PHYSICSCODE_EXPERIMENTAL")
const PHYSICSCODE_DISABLE_CLAUDE_CODE = truthy("PHYSICSCODE_DISABLE_CLAUDE_CODE")
const PHYSICSCODE_DISABLE_CLAUDE_CODE_SKILLS =
  PHYSICSCODE_DISABLE_CLAUDE_CODE || truthy("PHYSICSCODE_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["PHYSICSCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  PHYSICSCODE_AUTO_SHARE: truthy("PHYSICSCODE_AUTO_SHARE"),
  PHYSICSCODE_AUTO_HEAP_SNAPSHOT: truthy("PHYSICSCODE_AUTO_HEAP_SNAPSHOT"),
  PHYSICSCODE_GIT_BASH_PATH: process.env["PHYSICSCODE_GIT_BASH_PATH"],
  PHYSICSCODE_CONFIG: process.env["PHYSICSCODE_CONFIG"],
  PHYSICSCODE_CONFIG_CONTENT: process.env["PHYSICSCODE_CONFIG_CONTENT"],
  PHYSICSCODE_DISABLE_AUTOUPDATE: truthy("PHYSICSCODE_DISABLE_AUTOUPDATE"),
  PHYSICSCODE_ALWAYS_NOTIFY_UPDATE: truthy("PHYSICSCODE_ALWAYS_NOTIFY_UPDATE"),
  PHYSICSCODE_DISABLE_PRUNE: truthy("PHYSICSCODE_DISABLE_PRUNE"),
  PHYSICSCODE_DISABLE_TERMINAL_TITLE: truthy("PHYSICSCODE_DISABLE_TERMINAL_TITLE"),
  PHYSICSCODE_SHOW_TTFD: truthy("PHYSICSCODE_SHOW_TTFD"),
  PHYSICSCODE_PERMISSION: process.env["PHYSICSCODE_PERMISSION"],
  PHYSICSCODE_DISABLE_DEFAULT_PLUGINS: truthy("PHYSICSCODE_DISABLE_DEFAULT_PLUGINS"),
  PHYSICSCODE_DISABLE_LSP_DOWNLOAD: truthy("PHYSICSCODE_DISABLE_LSP_DOWNLOAD"),
  PHYSICSCODE_ENABLE_EXPERIMENTAL_MODELS: truthy("PHYSICSCODE_ENABLE_EXPERIMENTAL_MODELS"),
  PHYSICSCODE_DISABLE_AUTOCOMPACT: truthy("PHYSICSCODE_DISABLE_AUTOCOMPACT"),
  PHYSICSCODE_DISABLE_MODELS_FETCH: truthy("PHYSICSCODE_DISABLE_MODELS_FETCH"),
  PHYSICSCODE_DISABLE_MOUSE: truthy("PHYSICSCODE_DISABLE_MOUSE"),
  PHYSICSCODE_DISABLE_CLAUDE_CODE,
  PHYSICSCODE_DISABLE_CLAUDE_CODE_PROMPT: PHYSICSCODE_DISABLE_CLAUDE_CODE || truthy("PHYSICSCODE_DISABLE_CLAUDE_CODE_PROMPT"),
  PHYSICSCODE_DISABLE_CLAUDE_CODE_SKILLS,
  PHYSICSCODE_DISABLE_EXTERNAL_SKILLS: truthy("PHYSICSCODE_DISABLE_EXTERNAL_SKILLS"),
  PHYSICSCODE_FAKE_VCS: process.env["PHYSICSCODE_FAKE_VCS"],
  PHYSICSCODE_SERVER_PASSWORD: process.env["PHYSICSCODE_SERVER_PASSWORD"],
  PHYSICSCODE_SERVER_USERNAME: process.env["PHYSICSCODE_SERVER_USERNAME"],
  PHYSICSCODE_ENABLE_QUESTION_TOOL: truthy("PHYSICSCODE_ENABLE_QUESTION_TOOL"),

  // Experimental
  PHYSICSCODE_EXPERIMENTAL,
  PHYSICSCODE_EXPERIMENTAL_FILEWATCHER: Config.boolean("PHYSICSCODE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  PHYSICSCODE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("PHYSICSCODE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  PHYSICSCODE_EXPERIMENTAL_ICON_DISCOVERY: PHYSICSCODE_EXPERIMENTAL || truthy("PHYSICSCODE_EXPERIMENTAL_ICON_DISCOVERY"),
  PHYSICSCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("PHYSICSCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  PHYSICSCODE_ENABLE_EXA: truthy("PHYSICSCODE_ENABLE_EXA") || PHYSICSCODE_EXPERIMENTAL || truthy("PHYSICSCODE_EXPERIMENTAL_EXA"),
  PHYSICSCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("PHYSICSCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  PHYSICSCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("PHYSICSCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  PHYSICSCODE_EXPERIMENTAL_OXFMT: PHYSICSCODE_EXPERIMENTAL || truthy("PHYSICSCODE_EXPERIMENTAL_OXFMT"),
  PHYSICSCODE_EXPERIMENTAL_LSP_TY: truthy("PHYSICSCODE_EXPERIMENTAL_LSP_TY"),
  PHYSICSCODE_EXPERIMENTAL_LSP_TOOL: PHYSICSCODE_EXPERIMENTAL || truthy("PHYSICSCODE_EXPERIMENTAL_LSP_TOOL"),
  PHYSICSCODE_EXPERIMENTAL_PLAN_MODE: PHYSICSCODE_EXPERIMENTAL || truthy("PHYSICSCODE_EXPERIMENTAL_PLAN_MODE"),
  PHYSICSCODE_EXPERIMENTAL_MARKDOWN: !falsy("PHYSICSCODE_EXPERIMENTAL_MARKDOWN"),
  PHYSICSCODE_MODELS_URL: process.env["PHYSICSCODE_MODELS_URL"],
  PHYSICSCODE_MODELS_PATH: process.env["PHYSICSCODE_MODELS_PATH"],
  PHYSICSCODE_DISABLE_EMBEDDED_WEB_UI: truthy("PHYSICSCODE_DISABLE_EMBEDDED_WEB_UI"),
  PHYSICSCODE_DB: process.env["PHYSICSCODE_DB"],
  PHYSICSCODE_DISABLE_CHANNEL_DB: truthy("PHYSICSCODE_DISABLE_CHANNEL_DB"),
  PHYSICSCODE_SKIP_MIGRATIONS: truthy("PHYSICSCODE_SKIP_MIGRATIONS"),
  PHYSICSCODE_STRICT_CONFIG_DEPS: truthy("PHYSICSCODE_STRICT_CONFIG_DEPS"),

  PHYSICSCODE_WORKSPACE_ID: process.env["PHYSICSCODE_WORKSPACE_ID"],
  PHYSICSCODE_EXPERIMENTAL_HTTPAPI: truthy("PHYSICSCODE_EXPERIMENTAL_HTTPAPI"),
  PHYSICSCODE_EXPERIMENTAL_WORKSPACES: PHYSICSCODE_EXPERIMENTAL || truthy("PHYSICSCODE_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get PHYSICSCODE_DISABLE_PROJECT_CONFIG() {
    return truthy("PHYSICSCODE_DISABLE_PROJECT_CONFIG")
  },
  get PHYSICSCODE_TUI_CONFIG() {
    return process.env["PHYSICSCODE_TUI_CONFIG"]
  },
  get PHYSICSCODE_CONFIG_DIR() {
    return process.env["PHYSICSCODE_CONFIG_DIR"]
  },
  get PHYSICSCODE_PURE() {
    return truthy("PHYSICSCODE_PURE")
  },
  get PHYSICSCODE_PLUGIN_META_FILE() {
    return process.env["PHYSICSCODE_PLUGIN_META_FILE"]
  },
  get PHYSICSCODE_CLIENT() {
    return process.env["PHYSICSCODE_CLIENT"] ?? "cli"
  },
}
